### ISSUE TITLE
nginx controller return error due to invalid pathType Prefix

### ISSUE THREAD

**Issue by natthan-pigoux** [DIRACGrid/diracx-charts#139]
Here is a example of a minimal-ingress.yaml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-example.zeuthen.desy.de
    http:
      paths:
      - path: /.well-known
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```
When deploying it using `kubectl apply -f minimal-ingress.yaml`:
```
W0204 11:30:55.815720   50364 warnings.go:70] path /.well-known cannot be used with pathType Prefix
Error: INSTALLATION FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /.well-known cannot be used with pathType Prefix
```
