### ISSUE TITLE
Get a certificate from letsEncrypt

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/diracx-charts#95]
Just make sure that this actually works

**Comment by natthan-pigoux** [comment]
FYI, I used the letsencrypt cluster issuer like this:

`charts > cert-manager-issuer > _issuer.yaml`:

```
{{- if index .Values "cluster-issuer" "enabled" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: diracx-ca
spec:
dnsNames:
    {{- range index .Values "cluster-issuer" "dnsNames" }}
    - {{ . }}
    {{- end }}
secretName: root-secret
commonName: diracx-ca
privateKey:
    algorithm: ECDSA
    size: 256
issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
{{- end }}

```
`charts > cert-manager-issuer > values.yaml`
```
cluster-issuer:
    enabled: true
    dnsNames:
        - vault.cta-test.zeuthen.desy.de
```
Then remove the usage of the  `diracx-ca-issuer` in the ingress definition anotations:
```
kind: Ingress
metadata:
name: {{ $fullName }}
labels:
    {{- include "diracx.labels" . | nindent 4 }}
annotations:
# {{- if index .Values "cert-manager-issuer" "enabled" }}
#   cert-manager.io/issuer: diracx-ca-issuer
# {{- end }}
```
Finally specify the use the cluster issuer: `ingress.annotations.cert-manager.io/cluster-issuer=letsencrypt-issuer`

Maybe there is a better way of doing it but its working for me.
